// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewApplication struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	JobID string `json:"jobID"`
	CvURL string `json:"cvURL"`
}
type NewJob struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Location    string `json:"location"`
	CreatedByID string `json:"createdByID"`
}
